version: '3.1'

services:
  web:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    ports:
      - "80:${PORT}"
    volumes:
      - .:/usr/src/app:delegated
